[package]
name = "concord"
version = "1.0.0"
edition = "2018"

[dependencies]
librustlet = { git = "http://github.com/37miners/rustlet", tag = "0.0.1" }
concordlib = { path = "./concord" }
data = { path = "./data" }
